### ISSUE TITLE
Crash in ole_variant2val

### ISSUE THREAD

**Issue by tallakt** [chef-boneyard/pr-win32ole#1]
variant:
  "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
var:
  [8200, 0, 0, 0, 434464, 0]

  x:/ruby_dcom_opc/pr-win32ole/lib/pr/win32ole.rb:739:in `[]=': can't convert Fixnum into String (TypeError)
          from x:/ruby_dcom_opc/pr-win32ole/lib/pr/win32ole.rb:739:in`ole_variant2val'
          from x:/ruby_dcom_opc/pr-win32ole/lib/pr/win32ole.rb:1814:in `ole_invoke'
          from x:/ruby_dcom_opc/pr-win32ole/lib/pr/win32ole.rb:1913:in`method_missing'
          from test.rb:15

Hope this is enough. Cheers, Tallak

**Comment by djberg96** [comment]
Odd, both 739 and 1814 are blank lines in the source. Line 1913 is the setproperty method, not method_missing.

Can you paste a code snippet that duplicates the error?

**Comment by tallakt** [comment]
Sorry - I had modified the code a bit to print the values, thus the line numbers were off..

```
x:/ruby_dcom_opc/pr-win32ole/lib/pr/win32ole.rb:735:in `[]=': can't convert Fixnum into String (TypeError)
    from x:/ruby_dcom_opc/pr-win32ole/lib/pr/win32ole.rb:735:in `ole_variant2val'
    from x:/ruby_dcom_opc/pr-win32ole/lib/pr/win32ole.rb:1810:in `ole_invoke'
    from x:/ruby_dcom_opc/pr-win32ole/lib/pr/win32ole.rb:1909:in `method_missing'
    from test.rb:15
```

   #!/usr/bin/env ruby
   #require 'win32ole'
   require 'rubygems'
   require 'x:/ruby_dcom_opc/pr-win32ole/lib/pr/win32ole'

   opc_automation = WIN32OLE.new 'Opc.Automation'
   p opc_automation.GetOPCServers # ok

   opc_automation.connect 'Matrikon.OPC.Simulation', 'test.rb'
   groups = opc_automation.OPCGroups
   group = groups.add 'test_rb_group'

   items = Object.new
   errors = Object.new
   group.OPCItems.AddItems 1, ['', 'Random.Int1'], [0, 1], items, errors

**Comment by cgunasree08** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
